### ISSUE TITLE
Fails at run-time: No module named 'qjackcapture.ui_mainwindow'

### ISSUE THREAD

**Issue by yurivict** [SpotlightKid/qjackcapture#2]
```
$ qjackcapture 
Traceback (most recent call last):
  File "/usr/local/bin/qjackcapture", line 33, in <module>
    sys.exit(load_entry_point('QJackCapture==0.2.0', 'console_scripts', 'qjackcapture')())
  File "/usr/local/bin/qjackcapture", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/local/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/site-packages/qjackcapture/app.py", line 73, in <module>
    from .ui_mainwindow import Ui_MainWindow
ModuleNotFoundError: No module named 'qjackcapture.ui_mainwindow'
```

It is built with ```setup.py build```.

It installs the following files:
```
$ pkg info -l qjackcapture
qjackcapture-0.2.0:
	/usr/local/bin/qjackcapture
	/usr/local/lib/python3.9/site-packages/QJackCapture-0.2.0-py3.9.egg-info/PKG-INFO
	/usr/local/lib/python3.9/site-packages/QJackCapture-0.2.0-py3.9.egg-info/SOURCES.txt
	/usr/local/lib/python3.9/site-packages/QJackCapture-0.2.0-py3.9.egg-info/dependency_links.txt
	/usr/local/lib/python3.9/site-packages/QJackCapture-0.2.0-py3.9.egg-info/entry_points.txt
	/usr/local/lib/python3.9/site-packages/QJackCapture-0.2.0-py3.9.egg-info/not-zip-safe
	/usr/local/lib/python3.9/site-packages/QJackCapture-0.2.0-py3.9.egg-info/requires.txt
	/usr/local/lib/python3.9/site-packages/QJackCapture-0.2.0-py3.9.egg-info/top_level.txt
	/usr/local/lib/python3.9/site-packages/qjackcapture/__main__.py
	/usr/local/lib/python3.9/site-packages/qjackcapture/__pycache__/__main__.cpython-39.opt-1.pyc
	/usr/local/lib/python3.9/site-packages/qjackcapture/__pycache__/__main__.cpython-39.pyc
	/usr/local/lib/python3.9/site-packages/qjackcapture/__pycache__/app.cpython-39.opt-1.pyc
	/usr/local/lib/python3.9/site-packages/qjackcapture/__pycache__/app.cpython-39.pyc
	/usr/local/lib/python3.9/site-packages/qjackcapture/__pycache__/userdirs.cpython-39.opt-1.pyc
	/usr/local/lib/python3.9/site-packages/qjackcapture/__pycache__/userdirs.cpython-39.pyc
	/usr/local/lib/python3.9/site-packages/qjackcapture/__pycache__/version.cpython-39.opt-1.pyc
	/usr/local/lib/python3.9/site-packages/qjackcapture/__pycache__/version.cpython-39.pyc
	/usr/local/lib/python3.9/site-packages/qjackcapture/app.py
	/usr/local/lib/python3.9/site-packages/qjackcapture/userdirs.py
	/usr/local/lib/python3.9/site-packages/qjackcapture/version.py
	/usr/local/share/licenses/qjackcapture-0.2.0/GPLv2
	/usr/local/share/licenses/qjackcapture-0.2.0/LICENSE
	/usr/local/share/licenses/qjackcapture-0.2.0/catalog.mk
```

**Comment by SpotlightKid** [comment]
You need to build the UI files with `make`,

As noted in the readme, you can just do:

    make
    [sudo] make PREFIX=/usr install

Instead you can also create a wheel file with `make wheel` and install the resulting `.whl` file placed in `dist` with any PEP-517 compatible installer, e.g. `pip`, but then you'll miss the installation of the `.desktop` file and the icon.

**Comment by yurivict** [comment]
```make install``` fails:
```
gmake[1]: Entering directory '/disk-samsung/freebsd-ports/audio/qjackcapture/work/qjackcapture-0.2.0'
install -Dm644 resources/icons/48x48/qjackcapture.png -t /disk-samsung/freebsd-ports/audio/qjackcapture/work/stage/usr/local/share/icons/hicolor/48x48/apps
install: target directory `/disk-samsung/freebsd-ports/audio/qjackcapture/work/stage/usr/local/share/icons/hicolor/48x48/apps' does not exist
usage: install [-bCcpSsUv] [-f flags] [-g group] [-m mode] [-o owner]
               [-M log] [-D dest] [-h hash] [-T tags]
               [-B suffix] [-l linkflags] [-N dbdir]
               file1 file2
       install [-bCcpSsUv] [-f flags] [-g group] [-m mode] [-o owner]
               [-M log] [-D dest] [-h hash] [-T tags]
               [-B suffix] [-l linkflags] [-N dbdir]
               file1 ... fileN directory
       install -dU [-vU] [-g group] [-m mode] [-N dbdir] [-o owner]
               [-M log] [-D dest] [-h hash] [-T tags]
               directory ...
gmake[1]: *** [Makefile:51: install-data] Error 64
gmake[1]: Leaving directory '/disk-samsung/freebsd-ports/audio/qjackcapture/work/qjackcapture-0.2.0'
*** Error code 2
```

**Comment by SpotlightKid** [comment]
It seems `install` on BSD does not support the `-t` parameter (which is really annoying).

I just pushed a fix for the Makefile: 96eb5be

**Comment by yurivict** [comment]
The latest commit still fails because of ```-t```.

**Comment by SpotlightKid** [comment]
Sorry, missed that in the hurry. Removed now.

**Comment by yurivict** [comment]
Thanks for fixing this!
